### ISSUE TITLE
ゲイという単語について

### ISSUE THREAD

**Issue by 5ee1e** [MosasoM/inappropriate-words-ja#1]
ゲイというのは、ただただ男性が男性を好きであることであるから外してもよいと思う

**Comment by MosasoM** [comment]
わたしも悩んだのですが、

真面目な文章ではポリコレ的にゲイを使うことはあまりない(ヘテロ/ホモもしくはLGBTやセクシャルマイノリティの方が多い)ということで残しておりました。

ただ自分の観測範囲での話ですし、不快に思う方もいらっしゃいそうなので、外すことに致します。
