### ISSUE TITLE
69（シックスナイン）

### ISSUE THREAD

**Issue by Azunyan1111** [MosasoM/inappropriate-words-ja#2]
69
シックスナイン

https://ja.m.wikipedia.org/wiki/%E3%82%B7%E3%83%83%E3%82%AF%E3%82%B9%E3%83%8A%E3%82%A4%E3%83%B3

**Comment by MosasoM** [comment]
ありがとうございます。見落としておりました。

69の方は偽陽性の問題が少し気になるので(偽陽性を低く抑えようとデータベース化しているので)
シックスナインの方を追加いたします。
