### ISSUE TITLE
表示順に規則性を持たせたい

### ISSUE THREAD

**Issue by uhooi** [MosasoM/inappropriate-words-ja#4]
不適切な表現をまとめてくださりありがとうございます。

---

`R18.txt` 内の単語の表示順に規則性がないのが気になります。
例えば「ちんちん」「ちんこ」「ちんぽ」は近い位置にあると見やすいです。

文字コード順が望ましいと思ったのですが、そうすると「ちんちん」と「おちんちん」が遠い位置になるなどのデメリットもあるかもしれません。
個人的には「ちんちん」があれば「おちんちん」は不要だと感じたのですが、自然言語処理によっては必要なのでしょうか。

**Comment by MosasoM** [comment]
表示順については、たしかに悩みどころですね...

ただ、管理の手間を考えると文字コード順でソートしてしまうのが楽そうなので文字コード順で対応したいと思います。
(just ideaとしては、2文字以上共通する単語ごとでグルーピングしたあとに文字コードソートとかが良さそうかな?などは思ったのですが、見る側に余計なアルゴリズム解釈的負担を与えそうなので…)

「ちんちん」、「おちんちん」の問題については、単純に正規表現でテキスト中に存在するかどうかを見る場合には等価ですが、テキスト中に存在するかどうかだけを見る手法では、

会話文の

「〜確かにそうですしね、」

の「しね」が「死ね」だと捉えられるみたいな問題が起きます。
そこで、これらを排除するために形態素解析をしたあとに完全一致で判定したい場合が存在すると考えているので、可能な限りの表記ゆれは含むようにしている次第です

**Comment by uhooi** [comment]
ご返信ありがとうございます！

> 文字コード順で対応したいと思います

> 可能な限りの表記ゆれは含むようにしている

どちらも承知しました。いいと思いますー！
