### ISSUE TITLE
注音符号を用いた不適切ワードの追加

### ISSUE THREAD

**Issue by Meiryo7743** [MosasoM/inappropriate-words-ja#6]
注音符号（[Wikipedia](https://ja.wikipedia.org/wiki/%E6%B3%A8%E9%9F%B3%E7%AC%A6%E5%8F%B7)）という，主に台湾で使われる中国語の発音記号があります。

ひらがな・カタカナに近い形の字が存在するため，それを利用して不適切ワードを回避するケースがあるようです。ただ，考えられる回避パターンが多数ありそうなので，網羅するのは難しいかもしれません。

## 似ている字の例

|日本語|注音符号|
|---|---|
|エ|ㆲ|
|く|ㄑ|
|さ|ㄛ，ㄜ|
|セ|ㆤ，ㆥ|
|ち|ㄘ，ㄎ，ㆶ|
|ヌ|ㄡ|
|ム|ㄙ|
|ろ|ㄋ|

## 不適切ワードの例

|日本語|注音符号|
|---|---|
|ちんちん|ㄘんㄘん，ちんㄘん|
|せっくす|ㄝっくす，ㆤっくす|
|ヌく|ㄡく，ㄡㄑ|

**Comment by MosasoM** [comment]
情報ありがとうございます。
Twitterとかでたまに見るのは注音符号だったんですね。

こちら、可能な限り機械的に全パターン生成することを検討してみます。
(元の単語が〜300程度なので、全パターン生成してもそこまで爆発的にはならないと思うのでやってみます)


-追記-
Sexual_with_bopomofo.txtに上記の対応をしてみましたがいかがでしょうか

**Comment by Meiryo7743** [comment]
> Sexual_with_bopomofo.txtに上記の対応をしてみましたがいかがでしょうか

早速拝見しました。特に問題はないように見えます。
余談ですが，単語のバリエーションの多さに思わず吹き出してしまいました。様々な表現があるんですね……。

**Comment by MosasoM** [comment]
ご確認のほどありがとうございます。

そうなんです、収集してて思ったのですが淫語の類いって罵倒語とかに比べてもかなり多様なんですよね…
(これでも官能小説等で使われるようなより文学的表現は収集できてないのでまだ少ないです…)
これからもちょくちょく見つけるたびに拡充していこうと思っています。

Issue Close致しますね。
